Add support for building with CMake.
hunspell/hunspell pull request #617
Opened 2018-12-20 18:51 UTC by pzmarius

Tested to work on Windows, Linux and macOS. 

The following options `HUNSPELL_BUILD_TOOLS` and `HUNSPELL_BUILD_STATIC` are provided to selectively build the hunspell tools (including parsers), as well as the static version of libhunspell, respectively. `HUNSPELL_TOOLS_OUTPUT_PREFIX` can be used to add a prefix to the built executables output name, resolving the name conflict issue mentioned in PR #605.

The latest Visual Studio generators can be used to generate a multi-config solution on Windows. This renderes the project files already present in source tree under `msvc/` as unnecessary.

The `po/` and `test/` directories are not included in the current script, though it can be extended to also process `po` files, as CMake provides modules for handling `gettext`.

There is an issue when building hunspell on Mac, where ncurses cannot be found even when installed correctly using homebrew. This is because the CMake package `FindCurses` used to find ncurses fails to find the required libraries and paths. Everything works OK when paths are set manually during configuration. Also worth noting that the latest readline package in homebrew is not compatible with the current code that uses it, due to missing identifiers: `rl_delete_text()`, `rl_done`, `rl_set_key()`. Haven't tried with previous versions of the readline library.

The `hunspell.cxx` tool source file was slightly modified to keep the Clang compiler on Apple happy.

2020-05-02 11:40 UTC, zdenop commented
+1

2021-01-06 02:55 UTC, trailblazing requested changes
1. src/hunspell/CMakeLists.txt:92
`#   $<$<CXX_COMPILER_ID:Clang>:-Wl,-no-undefined,error>`
This setting does not work on Void Linux (musl). It's not necessary for the system.

2. src/hunspell/CMakeLists.txt:101
`VERSION      0.0.${PROJECT_VERSION_PATCH}  # ${PROJECT_VERSION}`
If I set project version to 1.7.2, the patch version would be 2. We will get "libhunspell-1.7.so.0.0.2". Otherwise from the original version setting we got "libhunspell-1.7.so.1.7.0"

3. src/hunspell/CMakeLists.txt:161
`VERSION      0.0.${PROJECT_VERSION_PATCH}  # ${PROJECT_VERSION}`
Same as above.

2022-11-25 06:04 UTC, zdenop commented
@caolanm: please can you merge this?

2022-12-29 21:00 UTC, zdenop commented
as version [v1.7.2](https://github.com/hunspell/hunspell/releases/tag/v1.7.2) was released - can you please add this cmake support, so we can improve it? e.g we can remove https://github.com/hunspell/hunspell/tree/master/msvc afterwords...?

2026-05-04 12:12 UTC, caolanm commented
This looks superseded by #704

2026-05-04 12:12 UTC, closed without merging